# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
#from . import *
#from * import *
#from swagger_server import util
from .goldstone_interfaces_portbreakoutconfig_breakout import GoldstoneInterfacesPortbreakoutconfigBreakout
from .goldstone_interfaces_oper_status_enumeration import GoldstoneInterfacesOperStatusEnumeration
from .goldstone_interfaces_admin_status_enumeration import GoldstoneInterfacesAdminStatusEnumeration
from .goldstone_interfaces_interface_type_enumeration import GoldstoneInterfacesInterfaceTypeEnumeration
from .goldstone_interfaces_fec_enumeration import GoldstoneInterfacesFecEnumeration
from .goldstone_interfaces_auto_nego_enumeration import GoldstoneInterfacesAutoNegoEnumeration


class GoldstoneInterfacesInterfacesInterface(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, breakout: GoldstoneInterfacesPortbreakoutconfigBreakout=None, oper_status: GoldstoneInterfacesOperStatusEnumeration=None, admin_status: GoldstoneInterfacesAdminStatusEnumeration=None, interface_type: GoldstoneInterfacesInterfaceTypeEnumeration=None, fec: GoldstoneInterfacesFecEnumeration=None, lanes: str=None, name: str=None, alias: str=None, description: str=None, speed: int=None, if_index: int=None, auto_nego: GoldstoneInterfacesAutoNegoEnumeration=None):  # noqa: E501
        """GoldstoneInterfacesInterfacesInterface - a model defined in Swagger

        :param breakout: The breakout of this GoldstoneInterfacesInterfacesInterface.  # noqa: E501
        :type breakout: GoldstoneInterfacesPortbreakoutconfigBreakout
        :param oper_status: The oper_status of this GoldstoneInterfacesInterfacesInterface.  # noqa: E501
        :type oper_status: GoldstoneInterfacesOperStatusEnumeration
        :param admin_status: The admin_status of this GoldstoneInterfacesInterfacesInterface.  # noqa: E501
        :type admin_status: GoldstoneInterfacesAdminStatusEnumeration
        :param interface_type: The interface_type of this GoldstoneInterfacesInterfacesInterface.  # noqa: E501
        :type interface_type: GoldstoneInterfacesInterfaceTypeEnumeration
        :param fec: The fec of this GoldstoneInterfacesInterfacesInterface.  # noqa: E501
        :type fec: GoldstoneInterfacesFecEnumeration
        :param lanes: The lanes of this GoldstoneInterfacesInterfacesInterface.  # noqa: E501
        :type lanes: str
        :param name: The name of this GoldstoneInterfacesInterfacesInterface.  # noqa: E501
        :type name: str
        :param alias: The alias of this GoldstoneInterfacesInterfacesInterface.  # noqa: E501
        :type alias: str
        :param description: The description of this GoldstoneInterfacesInterfacesInterface.  # noqa: E501
        :type description: str
        :param speed: The speed of this GoldstoneInterfacesInterfacesInterface.  # noqa: E501
        :type speed: int
        :param if_index: The if_index of this GoldstoneInterfacesInterfacesInterface.  # noqa: E501
        :type if_index: int
        :param auto_nego: The auto_nego of this GoldstoneInterfacesInterfacesInterface.  # noqa: E501
        :type auto_nego: GoldstoneInterfacesAutoNegoEnumeration
        """
        self.swagger_types = {
            'breakout': GoldstoneInterfacesPortbreakoutconfigBreakout,
            'oper_status': GoldstoneInterfacesOperStatusEnumeration,
            'admin_status': GoldstoneInterfacesAdminStatusEnumeration,
            'interface_type': GoldstoneInterfacesInterfaceTypeEnumeration,
            'fec': GoldstoneInterfacesFecEnumeration,
            'lanes': str,
            'name': str,
            'alias': str,
            'description': str,
            'speed': int,
            'if_index': int,
            'auto_nego': GoldstoneInterfacesAutoNegoEnumeration
        }

        self.attribute_map = {
            'breakout': 'breakout',
            'oper_status': 'oper-status',
            'admin_status': 'admin-status',
            'interface_type': 'interface-type',
            'fec': 'fec',
            'lanes': 'lanes',
            'name': 'name',
            'alias': 'alias',
            'description': 'description',
            'speed': 'speed',
            'if_index': 'if-index',
            'auto_nego': 'auto-nego'
        }

        self._breakout = breakout
        self._oper_status = oper_status
        self._admin_status = admin_status
        self._interface_type = interface_type
        self._fec = fec
        self._lanes = lanes
        self._name = name
        self._alias = alias
        self._description = description
        self._speed = speed
        self._if_index = if_index
        self._auto_nego = auto_nego

    @classmethod
    def from_dict(cls, dikt) -> 'GoldstoneInterfacesInterfacesInterface':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The goldstone.interfaces.interfaces.Interface of this GoldstoneInterfacesInterfacesInterface.  # noqa: E501
        :rtype: GoldstoneInterfacesInterfacesInterface
        """
        return util.deserialize_model(dikt, cls)

    @property
    def breakout(self) -> GoldstoneInterfacesPortbreakoutconfigBreakout:
        """Gets the breakout of this GoldstoneInterfacesInterfacesInterface.


        :return: The breakout of this GoldstoneInterfacesInterfacesInterface.
        :rtype: GoldstoneInterfacesPortbreakoutconfigBreakout
        """
        return self._breakout

    @breakout.setter
    def breakout(self, breakout: GoldstoneInterfacesPortbreakoutconfigBreakout):
        """Sets the breakout of this GoldstoneInterfacesInterfacesInterface.


        :param breakout: The breakout of this GoldstoneInterfacesInterfacesInterface.
        :type breakout: GoldstoneInterfacesPortbreakoutconfigBreakout
        """

        self._breakout = breakout

    @property
    def oper_status(self) -> GoldstoneInterfacesOperStatusEnumeration:
        """Gets the oper_status of this GoldstoneInterfacesInterfacesInterface.

        The current operational state of the interface.            This leaf has the same semantics as ifOperStatus. REF:RFC 2863: The Interfaces Group MIB - ifOperStatus  # noqa: E501

        :return: The oper_status of this GoldstoneInterfacesInterfacesInterface.
        :rtype: GoldstoneInterfacesOperStatusEnumeration
        """
        return self._oper_status

    @oper_status.setter
    def oper_status(self, oper_status: GoldstoneInterfacesOperStatusEnumeration):
        """Sets the oper_status of this GoldstoneInterfacesInterfacesInterface.

        The current operational state of the interface.            This leaf has the same semantics as ifOperStatus. REF:RFC 2863: The Interfaces Group MIB - ifOperStatus  # noqa: E501

        :param oper_status: The oper_status of this GoldstoneInterfacesInterfacesInterface.
        :type oper_status: GoldstoneInterfacesOperStatusEnumeration
        """

        self._oper_status = oper_status

    @property
    def admin_status(self) -> GoldstoneInterfacesAdminStatusEnumeration:
        """Gets the admin_status of this GoldstoneInterfacesInterfacesInterface.

        The desired state of the interface.             This leaf has the same read semantics as ifAdminStatus. REF:RFC 2863: The Interfaces Group MIB - ifAdminStatus  # noqa: E501

        :return: The admin_status of this GoldstoneInterfacesInterfacesInterface.
        :rtype: GoldstoneInterfacesAdminStatusEnumeration
        """
        return self._admin_status

    @admin_status.setter
    def admin_status(self, admin_status: GoldstoneInterfacesAdminStatusEnumeration):
        """Sets the admin_status of this GoldstoneInterfacesInterfacesInterface.

        The desired state of the interface.             This leaf has the same read semantics as ifAdminStatus. REF:RFC 2863: The Interfaces Group MIB - ifAdminStatus  # noqa: E501

        :param admin_status: The admin_status of this GoldstoneInterfacesInterfacesInterface.
        :type admin_status: GoldstoneInterfacesAdminStatusEnumeration
        """

        self._admin_status = admin_status

    @property
    def interface_type(self) -> GoldstoneInterfacesInterfaceTypeEnumeration:
        """Gets the interface_type of this GoldstoneInterfacesInterfacesInterface.


        :return: The interface_type of this GoldstoneInterfacesInterfacesInterface.
        :rtype: GoldstoneInterfacesInterfaceTypeEnumeration
        """
        return self._interface_type

    @interface_type.setter
    def interface_type(self, interface_type: GoldstoneInterfacesInterfaceTypeEnumeration):
        """Sets the interface_type of this GoldstoneInterfacesInterfacesInterface.


        :param interface_type: The interface_type of this GoldstoneInterfacesInterfacesInterface.
        :type interface_type: GoldstoneInterfacesInterfaceTypeEnumeration
        """

        self._interface_type = interface_type

    @property
    def fec(self) -> GoldstoneInterfacesFecEnumeration:
        """Gets the fec of this GoldstoneInterfacesInterfacesInterface.


        :return: The fec of this GoldstoneInterfacesInterfacesInterface.
        :rtype: GoldstoneInterfacesFecEnumeration
        """
        return self._fec

    @fec.setter
    def fec(self, fec: GoldstoneInterfacesFecEnumeration):
        """Sets the fec of this GoldstoneInterfacesInterfacesInterface.


        :param fec: The fec of this GoldstoneInterfacesInterfacesInterface.
        :type fec: GoldstoneInterfacesFecEnumeration
        """

        self._fec = fec

    @property
    def lanes(self) -> str:
        """Gets the lanes of this GoldstoneInterfacesInterfacesInterface.

        Todo REF:Todo  # noqa: E501

        :return: The lanes of this GoldstoneInterfacesInterfacesInterface.
        :rtype: str
        """
        return self._lanes

    @lanes.setter
    def lanes(self, lanes: str):
        """Sets the lanes of this GoldstoneInterfacesInterfacesInterface.

        Todo REF:Todo  # noqa: E501

        :param lanes: The lanes of this GoldstoneInterfacesInterfacesInterface.
        :type lanes: str
        """

        self._lanes = lanes

    @property
    def name(self) -> str:
        """Gets the name of this GoldstoneInterfacesInterfacesInterface.

        The name of the interface.             A device MAY restrict the allowed values for this leaf,            possibly depending on the type of the interface.            For system-controlled interfaces, this leaf is the            device-specific name of the interface.             If a client tries to create configuration for a            system-controlled interface that is not present in the            operational state, the server MAY reject the request if            the implementation does not support pre-provisioning of            interfaces or if the name refers to an interface that can            never exist in the system.  A Network Configuration            Protocol (NETCONF) server MUST reply with an rpc-error            with the error-tag 'invalid-value' in this case.             If the device supports pre-provisioning of interface            configuration, the 'pre-provisioning' feature is            advertised.             If the device allows arbitrarily named user-controlled            interfaces, the 'arbitrary-names' feature is advertised.             When a configured user-controlled interface is created by            the system, it is instantiated with the same name in the            operational state.             A server implementation MAY map this leaf to the ifName            MIB object.  Such an implementation needs to use some            mechanism to handle the differences in size and characters            allowed between this leaf and ifName.  The definition of            such a mechanism is outside the scope of this document. REF:RFC 2863: The Interfaces Group MIB - ifName  # noqa: E501

        :return: The name of this GoldstoneInterfacesInterfacesInterface.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this GoldstoneInterfacesInterfacesInterface.

        The name of the interface.             A device MAY restrict the allowed values for this leaf,            possibly depending on the type of the interface.            For system-controlled interfaces, this leaf is the            device-specific name of the interface.             If a client tries to create configuration for a            system-controlled interface that is not present in the            operational state, the server MAY reject the request if            the implementation does not support pre-provisioning of            interfaces or if the name refers to an interface that can            never exist in the system.  A Network Configuration            Protocol (NETCONF) server MUST reply with an rpc-error            with the error-tag 'invalid-value' in this case.             If the device supports pre-provisioning of interface            configuration, the 'pre-provisioning' feature is            advertised.             If the device allows arbitrarily named user-controlled            interfaces, the 'arbitrary-names' feature is advertised.             When a configured user-controlled interface is created by            the system, it is instantiated with the same name in the            operational state.             A server implementation MAY map this leaf to the ifName            MIB object.  Such an implementation needs to use some            mechanism to handle the differences in size and characters            allowed between this leaf and ifName.  The definition of            such a mechanism is outside the scope of this document. REF:RFC 2863: The Interfaces Group MIB - ifName  # noqa: E501

        :param name: The name of this GoldstoneInterfacesInterfacesInterface.
        :type name: str
        """

        self._name = name

    @property
    def alias(self) -> str:
        """Gets the alias of this GoldstoneInterfacesInterfacesInterface.

        Todo REF:Todo  # noqa: E501

        :return: The alias of this GoldstoneInterfacesInterfacesInterface.
        :rtype: str
        """
        return self._alias

    @alias.setter
    def alias(self, alias: str):
        """Sets the alias of this GoldstoneInterfacesInterfacesInterface.

        Todo REF:Todo  # noqa: E501

        :param alias: The alias of this GoldstoneInterfacesInterfacesInterface.
        :type alias: str
        """

        self._alias = alias

    @property
    def description(self) -> str:
        """Gets the description of this GoldstoneInterfacesInterfacesInterface.

        A textual description of the interface.             A server implementation MAY map this leaf to the ifAlias            MIB object.  Such an implementation needs to use some            mechanism to handle the differences in size and characters            allowed between this leaf and ifAlias.  The definition of            such a mechanism is outside the scope of this document.             Since ifAlias is defined to be stored in non-volatile            storage, the MIB implementation MUST map ifAlias to the            value of 'description' in the persistently stored            configuration. REF:RFC 2863: The Interfaces Group MIB - ifAlias  # noqa: E501

        :return: The description of this GoldstoneInterfacesInterfacesInterface.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this GoldstoneInterfacesInterfacesInterface.

        A textual description of the interface.             A server implementation MAY map this leaf to the ifAlias            MIB object.  Such an implementation needs to use some            mechanism to handle the differences in size and characters            allowed between this leaf and ifAlias.  The definition of            such a mechanism is outside the scope of this document.             Since ifAlias is defined to be stored in non-volatile            storage, the MIB implementation MUST map ifAlias to the            value of 'description' in the persistently stored            configuration. REF:RFC 2863: The Interfaces Group MIB - ifAlias  # noqa: E501

        :param description: The description of this GoldstoneInterfacesInterfacesInterface.
        :type description: str
        """

        self._description = description

    @property
    def speed(self) -> int:
        """Gets the speed of this GoldstoneInterfacesInterfacesInterface.

        An estimate of the interface's current bandwidth in bits              per second.  For interfaces that do not vary in              bandwidth or for those where no accurate estimation can              be made, this node should contain the nominal bandwidth.              For interfaces that have no concept of bandwidth, this              node is not present. REF:RFC 2863: The Interfaces Group MIB -                      ifSpeed, ifHighSpeed  # noqa: E501

        :return: The speed of this GoldstoneInterfacesInterfacesInterface.
        :rtype: int
        """
        return self._speed

    @speed.setter
    def speed(self, speed: int):
        """Sets the speed of this GoldstoneInterfacesInterfacesInterface.

        An estimate of the interface's current bandwidth in bits              per second.  For interfaces that do not vary in              bandwidth or for those where no accurate estimation can              be made, this node should contain the nominal bandwidth.              For interfaces that have no concept of bandwidth, this              node is not present. REF:RFC 2863: The Interfaces Group MIB -                      ifSpeed, ifHighSpeed  # noqa: E501

        :param speed: The speed of this GoldstoneInterfacesInterfacesInterface.
        :type speed: int
        """

        self._speed = speed

    @property
    def if_index(self) -> int:
        """Gets the if_index of this GoldstoneInterfacesInterfacesInterface.

        The ifIndex value for the ifEntry represented by this            interface. REF:RFC 2863: The Interfaces Group MIB - ifIndex  # noqa: E501

        :return: The if_index of this GoldstoneInterfacesInterfacesInterface.
        :rtype: int
        """
        return self._if_index

    @if_index.setter
    def if_index(self, if_index: int):
        """Sets the if_index of this GoldstoneInterfacesInterfacesInterface.

        The ifIndex value for the ifEntry represented by this            interface. REF:RFC 2863: The Interfaces Group MIB - ifIndex  # noqa: E501

        :param if_index: The if_index of this GoldstoneInterfacesInterfacesInterface.
        :type if_index: int
        """

        self._if_index = if_index

    @property
    def auto_nego(self) -> GoldstoneInterfacesAutoNegoEnumeration:
        """Gets the auto_nego of this GoldstoneInterfacesInterfacesInterface.


        :return: The auto_nego of this GoldstoneInterfacesInterfacesInterface.
        :rtype: GoldstoneInterfacesAutoNegoEnumeration
        """
        return self._auto_nego

    @auto_nego.setter
    def auto_nego(self, auto_nego: GoldstoneInterfacesAutoNegoEnumeration):
        """Sets the auto_nego of this GoldstoneInterfacesInterfacesInterface.


        :param auto_nego: The auto_nego of this GoldstoneInterfacesInterfacesInterface.
        :type auto_nego: GoldstoneInterfacesAutoNegoEnumeration
        """

        self._auto_nego = auto_nego
