# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
#from swagger_server import util


class GoldstoneInterfacesPortbreakoutconfigBreakout(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, parent: str=None, channel_speed: str=None, num_channels: int=None):  # noqa: E501
        """GoldstoneInterfacesPortbreakoutconfigBreakout - a model defined in Swagger

        :param parent: The parent of this GoldstoneInterfacesPortbreakoutconfigBreakout.  # noqa: E501
        :type parent: str
        :param channel_speed: The channel_speed of this GoldstoneInterfacesPortbreakoutconfigBreakout.  # noqa: E501
        :type channel_speed: str
        :param num_channels: The num_channels of this GoldstoneInterfacesPortbreakoutconfigBreakout.  # noqa: E501
        :type num_channels: int
        """
        self.swagger_types = {
            'parent': str,
            'channel_speed': str,
            'num_channels': int
        }

        self.attribute_map = {
            'parent': 'parent',
            'channel_speed': 'channel-speed',
            'num_channels': 'num-channels'
        }

        self._parent = parent
        self._channel_speed = channel_speed
        self._num_channels = num_channels

    @classmethod
    def from_dict(cls, dikt) -> 'GoldstoneInterfacesPortbreakoutconfigBreakout':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The goldstone.interfaces.portbreakoutconfig.Breakout of this GoldstoneInterfacesPortbreakoutconfigBreakout.  # noqa: E501
        :rtype: GoldstoneInterfacesPortbreakoutconfigBreakout
        """
        return util.deserialize_model(dikt, cls)

    @property
    def parent(self) -> str:
        """Gets the parent of this GoldstoneInterfacesPortbreakoutconfigBreakout.


        :return: The parent of this GoldstoneInterfacesPortbreakoutconfigBreakout.
        :rtype: str
        """
        return self._parent

    @parent.setter
    def parent(self, parent: str):
        """Sets the parent of this GoldstoneInterfacesPortbreakoutconfigBreakout.


        :param parent: The parent of this GoldstoneInterfacesPortbreakoutconfigBreakout.
        :type parent: str
        """

        self._parent = parent

    @property
    def channel_speed(self) -> str:
        """Gets the channel_speed of this GoldstoneInterfacesPortbreakoutconfigBreakout.

        Sets the channel speed on each channel -- the           supported values are defined by the           ETHERNET_SPEED identity  # noqa: E501

        :return: The channel_speed of this GoldstoneInterfacesPortbreakoutconfigBreakout.
        :rtype: str
        """
        return self._channel_speed

    @channel_speed.setter
    def channel_speed(self, channel_speed: str):
        """Sets the channel_speed of this GoldstoneInterfacesPortbreakoutconfigBreakout.

        Sets the channel speed on each channel -- the           supported values are defined by the           ETHERNET_SPEED identity  # noqa: E501

        :param channel_speed: The channel_speed of this GoldstoneInterfacesPortbreakoutconfigBreakout.
        :type channel_speed: str
        """

        self._channel_speed = channel_speed

    @property
    def num_channels(self) -> int:
        """Gets the num_channels of this GoldstoneInterfacesPortbreakoutconfigBreakout.

        Sets the number of channels to 'breakout' on a port           capable of channelization  # noqa: E501

        :return: The num_channels of this GoldstoneInterfacesPortbreakoutconfigBreakout.
        :rtype: int
        """
        return self._num_channels

    @num_channels.setter
    def num_channels(self, num_channels: int):
        """Sets the num_channels of this GoldstoneInterfacesPortbreakoutconfigBreakout.

        Sets the number of channels to 'breakout' on a port           capable of channelization  # noqa: E501

        :param num_channels: The num_channels of this GoldstoneInterfacesPortbreakoutconfigBreakout.
        :type num_channels: int
        """

        self._num_channels = num_channels
