# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
#from swagger_server import util


class GoldstoneInterfacesInterfaceTypeEnumeration(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    SR = "SR"
    SR2 = "SR2"
    SR4 = "SR4"
    CR = "CR"
    CR2 = "CR2"
    CR4 = "CR4"
    LR = "LR"
    LR2 = "LR2"
    LR4 = "LR4"
    KR = "KR"
    KR2 = "KR2"
    KR4 = "KR4"

    def __init__(self):  # noqa: E501
        """GoldstoneInterfacesInterfaceTypeEnumeration - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'GoldstoneInterfacesInterfaceTypeEnumeration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The goldstone.interfaces.InterfaceTypeEnumeration of this GoldstoneInterfacesInterfaceTypeEnumeration.  # noqa: E501
        :rtype: GoldstoneInterfacesInterfaceTypeEnumeration
        """
        return util.deserialize_model(dikt, cls)
