# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .goldstone_interfaces_clearcounters_output import GoldstoneInterfacesClearcountersOutput
#from swagger_server import util


class GoldstoneInterfacesClearCounters(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, output: GoldstoneInterfacesClearcountersOutput=None):  # noqa: E501
        """GoldstoneInterfacesClearCounters - a model defined in Swagger

        :param output: The output of this GoldstoneInterfacesClearCounters.  # noqa: E501
        :type output: GoldstoneInterfacesClearcountersOutput
        """
        self.swagger_types = {
            'output': GoldstoneInterfacesClearcountersOutput
        }

        self.attribute_map = {
            'output': 'output'
        }

        self._output = output

    @classmethod
    def from_dict(cls, dikt) -> 'GoldstoneInterfacesClearCounters':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The goldstone.interfaces.ClearCounters of this GoldstoneInterfacesClearCounters.  # noqa: E501
        :rtype: GoldstoneInterfacesClearCounters
        """
        return util.deserialize_model(dikt, cls)

    @property
    def output(self) -> GoldstoneInterfacesClearcountersOutput:
        """Gets the output of this GoldstoneInterfacesClearCounters.


        :return: The output of this GoldstoneInterfacesClearCounters.
        :rtype: GoldstoneInterfacesClearcountersOutput
        """
        return self._output

    @output.setter
    def output(self, output: GoldstoneInterfacesClearcountersOutput):
        """Sets the output of this GoldstoneInterfacesClearCounters.


        :param output: The output of this GoldstoneInterfacesClearCounters.
        :type output: GoldstoneInterfacesClearcountersOutput
        """

        self._output = output
