# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .goldstone_interfaces_oper_status_enumeration import GoldstoneInterfacesOperStatusEnumeration
#from swagger_server import util


class GoldstoneInterfacesInterfaceOperStatus(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, oper_status: GoldstoneInterfacesOperStatusEnumeration=None):  # noqa: E501
        """GoldstoneInterfacesInterfaceOperStatus - a model defined in Swagger

        :param oper_status: The oper_status of this GoldstoneInterfacesInterfaceOperStatus.  # noqa: E501
        :type oper_status: GoldstoneInterfacesOperStatusEnumeration
        """
        self.swagger_types = {
            'oper_status': GoldstoneInterfacesOperStatusEnumeration
        }

        self.attribute_map = {
            'oper_status': 'oper-status'
        }

        self._oper_status = oper_status

    @classmethod
    def from_dict(cls, dikt) -> 'GoldstoneInterfacesInterfaceOperStatus':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The goldstone.interfaces.InterfaceOperStatus of this GoldstoneInterfacesInterfaceOperStatus.  # noqa: E501
        :rtype: GoldstoneInterfacesInterfaceOperStatus
        """
        return util.deserialize_model(dikt, cls)

    @property
    def oper_status(self) -> GoldstoneInterfacesOperStatusEnumeration:
        """Gets the oper_status of this GoldstoneInterfacesInterfaceOperStatus.

        The current operational state of the interface.            This leaf has the same semantics as ifOperStatus. REF:RFC 2863: The Interfaces Group MIB - ifOperStatus  # noqa: E501

        :return: The oper_status of this GoldstoneInterfacesInterfaceOperStatus.
        :rtype: GoldstoneInterfacesOperStatusEnumeration
        """
        return self._oper_status

    @oper_status.setter
    def oper_status(self, oper_status: GoldstoneInterfacesOperStatusEnumeration):
        """Sets the oper_status of this GoldstoneInterfacesInterfaceOperStatus.

        The current operational state of the interface.            This leaf has the same semantics as ifOperStatus. REF:RFC 2863: The Interfaces Group MIB - ifOperStatus  # noqa: E501

        :param oper_status: The oper_status of this GoldstoneInterfacesInterfaceOperStatus.
        :type oper_status: GoldstoneInterfacesOperStatusEnumeration
        """

        self._oper_status = oper_status
