# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .goldstone_interfaces_interfaces import GoldstoneInterfacesInterfaces
#from swagger_server import util


class GoldstoneInterfacesInterfacesWrapper(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, interfaces: GoldstoneInterfacesInterfaces=None):  # noqa: E501
        """GoldstoneInterfacesInterfacesWrapper - a model defined in Swagger

        :param interfaces: The interfaces of this GoldstoneInterfacesInterfacesWrapper.  # noqa: E501
        :type interfaces: GoldstoneInterfacesInterfaces
        """
        self.swagger_types = {
            'interfaces': GoldstoneInterfacesInterfaces
        }

        self.attribute_map = {
            'interfaces': 'interfaces'
        }

        self._interfaces = interfaces

    @classmethod
    def from_dict(cls, dikt) -> 'GoldstoneInterfacesInterfacesWrapper':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The goldstone.interfaces.InterfacesWrapper of this GoldstoneInterfacesInterfacesWrapper.  # noqa: E501
        :rtype: GoldstoneInterfacesInterfacesWrapper
        """
        return util.deserialize_model(dikt, cls)

    @property
    def interfaces(self) -> GoldstoneInterfacesInterfaces:
        """Gets the interfaces of this GoldstoneInterfacesInterfacesWrapper.


        :return: The interfaces of this GoldstoneInterfacesInterfacesWrapper.
        :rtype: GoldstoneInterfacesInterfaces
        """
        return self._interfaces

    @interfaces.setter
    def interfaces(self, interfaces: GoldstoneInterfacesInterfaces):
        """Sets the interfaces of this GoldstoneInterfacesInterfacesWrapper.


        :param interfaces: The interfaces of this GoldstoneInterfacesInterfacesWrapper.
        :type interfaces: GoldstoneInterfacesInterfaces
        """

        self._interfaces = interfaces
