# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .goldstone_interfaces_interfaces_interface import GoldstoneInterfacesInterfacesInterface

#from swagger_server import util


class GoldstoneInterfacesInterfacesInterfaceWrapper(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, interface: GoldstoneInterfacesInterfacesInterface=None):  # noqa: E501
        """GoldstoneInterfacesInterfacesInterfaceWrapper - a model defined in Swagger

        :param interface: The interface of this GoldstoneInterfacesInterfacesInterfaceWrapper.  # noqa: E501
        :type interface: GoldstoneInterfacesInterfacesInterface
        """
        self.swagger_types = {
            'interface': GoldstoneInterfacesInterfacesInterface
        }

        self.attribute_map = {
            'interface': 'interface'
        }

        self._interface = interface

    @classmethod
    def from_dict(cls, dikt) -> 'GoldstoneInterfacesInterfacesInterfaceWrapper':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The goldstone.interfaces.interfaces.InterfaceWrapper of this GoldstoneInterfacesInterfacesInterfaceWrapper.  # noqa: E501
        :rtype: GoldstoneInterfacesInterfacesInterfaceWrapper
        """
        return util.deserialize_model(dikt, cls)

    @property
    def interface(self) -> GoldstoneInterfacesInterfacesInterface:
        """Gets the interface of this GoldstoneInterfacesInterfacesInterfaceWrapper.


        :return: The interface of this GoldstoneInterfacesInterfacesInterfaceWrapper.
        :rtype: GoldstoneInterfacesInterfacesInterface
        """
        return self._interface

    @interface.setter
    def interface(self, interface: GoldstoneInterfacesInterfacesInterface):
        """Sets the interface of this GoldstoneInterfacesInterfacesInterfaceWrapper.


        :param interface: The interface of this GoldstoneInterfacesInterfacesInterfaceWrapper.
        :type interface: GoldstoneInterfacesInterfacesInterface
        """

        self._interface = interface
