# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .goldstone_interfaces_interfaces_interface import GoldstoneInterfacesInterfacesInterface
#from swagger_server import util


class GoldstoneInterfacesInterfaces(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, interface: List[GoldstoneInterfacesInterfacesInterface]=None):  # noqa: E501
        """GoldstoneInterfacesInterfaces - a model defined in Swagger

        :param interface: The interface of this GoldstoneInterfacesInterfaces.  # noqa: E501
        :type interface: List[GoldstoneInterfacesInterfacesInterface]
        """
        self.swagger_types = {
            'interface': List[GoldstoneInterfacesInterfacesInterface]
        }

        self.attribute_map = {
            'interface': 'interface'
        }

        self._interface = interface

    @classmethod
    def from_dict(cls, dikt) -> 'GoldstoneInterfacesInterfaces':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The goldstone.interfaces.Interfaces of this GoldstoneInterfacesInterfaces.  # noqa: E501
        :rtype: GoldstoneInterfacesInterfaces
        """
        return util.deserialize_model(dikt, cls)

    @property
    def interface(self) -> List[GoldstoneInterfacesInterfacesInterface]:
        """Gets the interface of this GoldstoneInterfacesInterfaces.

        The list of interfaces on the device.           The status of an interface is available in this list in the          operational state.  If the configuration of a          system-controlled interface cannot be used by the system          (e.g., the interface hardware present does not match the          interface type), then the configuration is not applied to          the system-controlled interface shown in the operational          state.  If the configuration of a user-controlled interface          cannot be used by the system, the configured interface is          not instantiated in the operational state.           System-controlled interfaces created by the system are          always present in this list in the operational state,          whether or not they are configured.  # noqa: E501

        :return: The interface of this GoldstoneInterfacesInterfaces.
        :rtype: List[GoldstoneInterfacesInterfacesInterface]
        """
        return self._interface

    @interface.setter
    def interface(self, interface: List[GoldstoneInterfacesInterfacesInterface]):
        """Sets the interface of this GoldstoneInterfacesInterfaces.

        The list of interfaces on the device.           The status of an interface is available in this list in the          operational state.  If the configuration of a          system-controlled interface cannot be used by the system          (e.g., the interface hardware present does not match the          interface type), then the configuration is not applied to          the system-controlled interface shown in the operational          state.  If the configuration of a user-controlled interface          cannot be used by the system, the configured interface is          not instantiated in the operational state.           System-controlled interfaces created by the system are          always present in this list in the operational state,          whether or not they are configured.  # noqa: E501

        :param interface: The interface of this GoldstoneInterfacesInterfaces.
        :type interface: List[GoldstoneInterfacesInterfacesInterface]
        """

        self._interface = interface
