# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
#from swagger_server import util


class GoldstoneInterfacesAutoNegoEnumeration(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    YES = "yes"
    NO = "no"

    def __init__(self):  # noqa: E501
        """GoldstoneInterfacesAutoNegoEnumeration - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'GoldstoneInterfacesAutoNegoEnumeration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The goldstone.interfaces.AutoNegoEnumeration of this GoldstoneInterfacesAutoNegoEnumeration.  # noqa: E501
        :rtype: GoldstoneInterfacesAutoNegoEnumeration
        """
        return util.deserialize_model(dikt, cls)
