# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
#from swagger_server import util


class GoldstoneInterfacesStatusEnumeration(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    allowed enum values
    """
    FALIURE = "faliure"
    SUCCESS = "success"

    def __init__(self):  # noqa: E501
        """GoldstoneInterfacesStatusEnumeration - a model defined in Swagger

        """
        self.swagger_types = {
        }

        self.attribute_map = {
        }

    @classmethod
    def from_dict(cls, dikt) -> 'GoldstoneInterfacesStatusEnumeration':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The goldstone.interfaces.StatusEnumeration of this GoldstoneInterfacesStatusEnumeration.  # noqa: E501
        :rtype: GoldstoneInterfacesStatusEnumeration
        """
        return util.deserialize_model(dikt, cls)
