# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .goldstone_interfaces_status_enumeration import GoldstoneInterfacesStatusEnumeration
#from swagger_server import util


class GoldstoneInterfacesClearcountersOutput(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, status: GoldstoneInterfacesStatusEnumeration):  # noqa: E501
        """GoldstoneInterfacesClearcountersOutput - a model defined in Swagger

        :param status: The status of this GoldstoneInterfacesClearcountersOutput.  # noqa: E501
        :type status: GoldstoneInterfacesStatusEnumeration
        """
        self.swagger_types = {
            'status': GoldstoneInterfacesStatusEnumeration
        }

        self.attribute_map = {
            'status': 'status'
        }

        self._status = status

    @classmethod
    def from_dict(cls, dikt) -> 'GoldstoneInterfacesClearcountersOutput':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The goldstone.interfaces.clearcounters.Output of this GoldstoneInterfacesClearcountersOutput.  # noqa: E501
        :rtype: GoldstoneInterfacesClearcountersOutput
        """
        return util.deserialize_model(dikt, cls)

    @property
    def status(self) -> GoldstoneInterfacesStatusEnumeration:
        """Gets the status of this GoldstoneInterfacesClearcountersOutput.


        :return: The status of this GoldstoneInterfacesClearcountersOutput.
        :rtype: GoldstoneInterfacesStatusEnumeration
        """
        return self._status

    @status.setter
    def status(self, status: GoldstoneInterfacesStatusEnumeration):
        """Sets the status of this GoldstoneInterfacesClearcountersOutput.


        :param status: The status of this GoldstoneInterfacesClearcountersOutput.
        :type status: GoldstoneInterfacesStatusEnumeration
        """

        self._status = status
