# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .goldstone_interfaces_portbreakoutconfig_breakout import GoldstoneInterfacesPortbreakoutconfigBreakout
#from swagger_server import util


class GoldstoneInterfacesPortbreakoutconfigBreakoutWrapper(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, breakout: GoldstoneInterfacesPortbreakoutconfigBreakout=None):  # noqa: E501
        """GoldstoneInterfacesPortbreakoutconfigBreakoutWrapper - a model defined in Swagger

        :param breakout: The breakout of this GoldstoneInterfacesPortbreakoutconfigBreakoutWrapper.  # noqa: E501
        :type breakout: GoldstoneInterfacesPortbreakoutconfigBreakout
        """
        self.swagger_types = {
            'breakout': GoldstoneInterfacesPortbreakoutconfigBreakout
        }

        self.attribute_map = {
            'breakout': 'breakout'
        }

        self._breakout = breakout

    @classmethod
    def from_dict(cls, dikt) -> 'GoldstoneInterfacesPortbreakoutconfigBreakoutWrapper':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The goldstone.interfaces.portbreakoutconfig.BreakoutWrapper of this GoldstoneInterfacesPortbreakoutconfigBreakoutWrapper.  # noqa: E501
        :rtype: GoldstoneInterfacesPortbreakoutconfigBreakoutWrapper
        """
        return util.deserialize_model(dikt, cls)

    @property
    def breakout(self) -> GoldstoneInterfacesPortbreakoutconfigBreakout:
        """Gets the breakout of this GoldstoneInterfacesPortbreakoutconfigBreakoutWrapper.


        :return: The breakout of this GoldstoneInterfacesPortbreakoutconfigBreakoutWrapper.
        :rtype: GoldstoneInterfacesPortbreakoutconfigBreakout
        """
        return self._breakout

    @breakout.setter
    def breakout(self, breakout: GoldstoneInterfacesPortbreakoutconfigBreakout):
        """Sets the breakout of this GoldstoneInterfacesPortbreakoutconfigBreakoutWrapper.


        :param breakout: The breakout of this GoldstoneInterfacesPortbreakoutconfigBreakoutWrapper.
        :type breakout: GoldstoneInterfacesPortbreakoutconfigBreakout
        """

        self._breakout = breakout
